apiVersion: v1 
kind: Service 
metadata: 
  name: my-app-service 
spec: 
  selector: 
    app: my-app            # This matches the label on Pods created by the Deployment 
  ports: 
    - protocol: TCP 
      port: 80             # The Service’s external port 
      targetPort: 3000     # The Pod’s container port 
  type: LoadBalancer 
