name: CI/CD Pipeline (self-hosted deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
# ─────────────────────────────────────────────────────────────
# BUILD & PUSH IMAGE - still on GitHub-hosted Ubuntu
# ─────────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max

# ─────────────────────────────────────────────────────────────
# DEPLOY TO KUBERNETES - runs on your self-hosted Windows runner
# ─────────────────────────────────────────────────────────────
  deploy:
    runs-on: [self-hosted, Windows, X64]
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl (pre-installed on the runner is fine; this ensures the right version)
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          $Env:KUBECONFIG = "$PWD\kubeconfig.yaml"
          echo "KUBECONFIG=$Env:KUBECONFIG" >> $Env:GITHUB_ENV

      # ─── DEBUG BLOCK ───────────────────────────────────────
      - name: Debug - show Kubernetes context & cluster-info
        run: |
          Write-Host ">>> kubectl config current-context"
          kubectl config current-context

          Write-Host "\n>>> kubectl config view --minify"
          kubectl config view --minify

          Write-Host "\n>>> kubectl cluster-info"
          kubectl cluster-info
      # ───────────────────────────────────────────────────────

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
