name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:        # allows manual “Run workflow”

# ─────────────────────────────────────────────────────────────────────────────
# BUILD  ─ runs on GitHub-hosted Ubuntu, builds & pushes Docker image
# ─────────────────────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max

# ─────────────────────────────────────────────────────────────────────────────
# DEPLOY  ─ runs on self-hosted Windows runner where Docker-Desktop cluster lives
# ─────────────────────────────────────────────────────────────────────────────
  deploy:
    needs: build
    runs-on: [ self-hosted, Windows, X64 ]   # labels of your local runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0          # pin a kubectl version

- name: Configure kubeconfig
  shell: powershell
  run: |
    # write secret to temp file
    '${{ secrets.KUBE_CONFIG }}' | Out-File kubeconfig.b64 -Encoding ascii

    # decode → kubeconfig.yaml
    certutil -f -decode kubeconfig.b64 kubeconfig.yaml | Out-Null

    # set env-var for later steps & GitHub job
    $Env:KUBECONFIG = "$PWD\kubeconfig.yaml"
    "KUBECONFIG=$Env:KUBECONFIG" | Out-File $Env:GITHUB_ENV -Encoding ascii -Append

# Optional debug
- name: Debug – show context & cluster info
  shell: powershell
  run: |
    kubectl config current-context || true
    kubectl cluster-info || true

      - name: Apply Kubernetes manifests
        shell: pwsh
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
