name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
# ────────────────────────────────────────────────────────────────────────────────
# BUILD & PUSH IMAGE
# ────────────────────────────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          cache-from: type=gha
          cache-to:   type=gha,mode=max

# ────────────────────────────────────────────────────────────────────────────────
# DEPLOY TO KUBERNETES
# ────────────────────────────────────────────────────────────────────────────────
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0          # pin the kubectl version you need

      # Decode the secret and point KUBECONFIG at it
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          echo "KUBECONFIG=$KUBECONFIG" >> "$GITHUB_ENV"

      # ─── DEBUG BLOCK ───────────────────────────────────────────────────
      - name: Debug - show current Kubernetes context & cluster-info
        run: |
          echo ">>> kubectl config current-context"
          kubectl config current-context || true

          echo -e "\n>>> kubectl config view --minify"
          kubectl config view --minify || true

          echo -e "\n>>> kubectl cluster-info"
          kubectl cluster-info || true
      # ──────────────────────────────────────────────────────────────────

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
