name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # build from the repo root (where your Dockerfile is)
          docker build --no-cache --pull \
            -t $DOCKERHUB_USERNAME/my-app:latest .
          
          # login & push
          echo "$DOCKERHUB_PASSWORD" | docker login \
            --username "$DOCKERHUB_USERNAME" \
            --password-stdin
          docker push $DOCKERHUB_USERNAME/my-app:latest

  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" \
            | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: kubectl apply
        run: |
          kubectl apply -f deployment.yaml
